export const COMMODITY_DETAILS_REQUEST = 'COMMODITY_DETAILS_REQUEST';
export const COMMODITY_DETAILS_SUCCESS = 'COMMODITY_DETAILS_SUCCESS';
export const COMMODITY_DETAILS_FAIL = 'COMMODITY_DETAILS_FAIL';
